const {sendMail} = require("../../mail/mail")

describe('CSRA Test', () => {
  it('all pages', () => {
    cy.visit('http://localhost:3001/')
    cy.get("div input#input_email").type("oluwateezzy03@gmail.com")
    cy.get("div input#input_password").type("12345678")
    cy.get("div button#sign_in").click()
    cy.wait(2000)

    cy.visit("http://localhost:3001/assessment_and_tips")
    cy.wait(2000)
    cy.visit("http://localhost:3001/application_introduction")
    cy.wait(2000)
    cy.visit("http://localhost:3001/environment_energy")
    cy.wait(2000)
    cy.visit("http://localhost:3001/environment_natural_resource")
    cy.wait(2000)
    cy.visit("http://localhost:3001/environment_travel")
    cy.wait(2000)
    cy.visit("http://localhost:3001/environment_supply_chain_management")
    cy.wait(2000)
    cy.visit("http://localhost:3001/environment_waste")
    cy.wait(2000)
    cy.visit("http://localhost:3001/environment_supporting_documents")
    cy.wait(2000)
    cy.visit("http://localhost:3001/workplace_training")
    cy.wait(2000)
    cy.visit("http://localhost:3001/workplace_labour_practices")
    cy.wait(2000)
    cy.visit("http://localhost:3001/workplace_ethical_practises")
    cy.wait(2000)
    cy.visit("http://localhost:3001/workplace_governance")
    cy.wait(2000)
    cy.visit("http://localhost:3001/workplace_policies")
    cy.wait(2000)

    cy.visit("http://localhost:3001/workplace_supporting_documents")
    cy.wait(2000)
    cy.visit("http://localhost:3001/community_engagement")
    cy.wait(2000)
    cy.visit("http://localhost:3001/community_local_issues")
    cy.wait(2000)
    cy.visit("http://localhost:3001/community_wealth_creation")
    cy.wait(2000)
    cy.visit("http://localhost:3001/community_projects_and_groups")
    cy.wait(2000)
    cy.visit("http://localhost:3001/community_education")
    cy.wait(2000)
    cy.visit("http://localhost:3001/philanthropy_charitable_involvement")
    cy.wait(2000)
    cy.visit("http://localhost:3001/philanthropy_volunteering")
    cy.wait(2000)
    cy.visit("http://localhost:3001/philanthropy_pro_bono")
    cy.wait(2000)
    cy.visit("http://localhost:3001/philanthropy_fund_raising")
    cy.wait(2000)
    cy.visit("http://localhost:3001/philanthropy_financial_and_kind_gifts")
    cy.wait(2000)
    cy.visit("http://localhost:3001/philanthropy_supporting_documents")
    cy.wait(2000)
    cy.visit("http://localhost:3001/further_information")
    cy.wait(2000)
  })

  it("Send Mail", () => {
    cy.visit('http://localhost:3001/')
    cy.get("div input#input_email").type("oluwateezzy03@gmail.com")
    cy.get("div input#input_password").type("12345678")
    cy.get("div button#sign_in").click()
    cy.wait(2000)

    cy.get("div button#submit_btn").click()

  })
})